# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Headplane systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ headplane_identifier }}.service"
  register: headplane_service_stat

- name: Uninstall Headplane systemd services and files
  when: headplane_service_stat.stat.exists | bool
  block:
    - name: Ensure Headplane systemd service is stopped
      ansible.builtin.service:
        name: "{{ headplane_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Headplane systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ headplane_identifier }}.service"
        state: absent

    - name: Ensure Headplane support files do not exist
      ansible.builtin.file:
        path: "{{ headplane_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Headplane local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ headplane_data_path }}"
      register: headplane_data_path_deletion_result
      changed_when: headplane_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Headplane local media path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ headplane_media_path }}"
      register: headplane_media_path_deletion_result
      changed_when: headplane_media_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Headplane base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ headplane_base_path }}"
      register: headplane_base_path_deletion_result
      changed_when: headplane_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Headplane container network does not exist
      when: headplane_container_network_deletion_enabled
      block:
        - name: Ensure Headplane container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ headplane_container_network }}"
            state: absent
          register: headplane_network_deletion_result

        - name: Ensure Headplane container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ headplane_container_network }}
          register: headplane_network_deletion_result
          changed_when: headplane_container_network in headplane_network_deletion_result.stdout

- name: Check existence of Headplane local data path
  ansible.builtin.stat:
    path: "{{ headplane_data_path }}"
  register: headplane_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Headplane local data path
  when: headplane_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Headplane instance has been removed, some old data remains in `" + headplane_data_path + "`. Feel free to delete it."
        ]
      }}
